language: php

dist: xenial

services:
  - mysql

addons:
  chrome: stable
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

php:
  - '7.4'

before_install:
  - chromium --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - composer clearcache
  - composer install
  - ./bin/phpunit install
  - yarn install
  - yarn encore dev

before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('secret_test') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -psecret_test
  - sudo service mysql restart
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:schema:create
  - ./bin/console hautelook:fixtures:load --no-interaction --no-debug

script:
  # run tests
  - ./bin/phpunit
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
