index:
  path: /
  controller: App\Controller\UserApp\Home\HomeController::homepage

searchPage:
  path: /search-page/
  controller: App\Controller\UserApp\Search\SearchController::searchPage
itemDetails:
  path: /details/
  controller: App\Controller\UserApp\Search\SearchController::detailsPage

loginUser:
  path: /user/login
  controller: App\Controller\UserApp\User\UserController::loginPage
register:
  path: /user/register
  controller: App\Controller\UserApp\User\UserController::registerPage
publication:
  path: /user/publication
  controller: App\Controller\UserApp\User\UserController::publicationPage
favorites:
  path: /user/favorites
  controller: App\Controller\UserApp\User\UserController::favoritesPage
manageAccountUser:
  path: /user/account-management
  controller: App\Controller\UserApp\User\UserController::manageAccountPage

loginAdmin:
  path: /admin/login
  controller: App\Controller\UserApp\Admin\AdminController::loginPage
manageAccountAdmin:
  path: /admin/account-management
  controller: App\Controller\UserApp\Admin\AdminController::manageAccountPage
usersManagement:
  path: /admin/users-management
  controller: App\Controller\UserApp\Admin\AdminController::manageUsers
announcementsManagement:
  path: /admin/announcements-management
  controller: App\Controller\UserApp\Admin\AdminController::manageAnnouncements
commentsManagement:
  path: /admin/comments-management
  controller: App\Controller\UserApp\Admin\AdminController::manageComments
dashboardAdmin:
  path: /admin/dashboard
  controller: App\Controller\UserApp\Admin\AdminController::dashboardPage

